[site]
title = "Qianli Wang"
description = "PhD student at Technische UniversitÃ¤t Berlin"
favicon = "/favicon.svg"
last_updated = "November 27, 2025"

[author]
name = "Qianli Wang"
title = "PhD Student"
institution = "Technische UniversitÃ¤t Berlin"
avatar = "/avatar.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "qianli.wang@tu-berlin.de"
location = "Berlin, Germany"
location_url = "https://maps.google.com"
location_details = [
  "Room 2.052, MAR Building",
  "MarchstraÃŸe 23, 10587 Berlin, Germany"
]
google_scholar = "https://scholar.google.com/citations?user=dKmUzp4AAAAJ"
#orcid = "https://orcid.org"
github = "https://github.com/qiaw99"
linkedin = "https://www.linkedin.com/in/qianliwang/"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "ğŸ“‘ Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "ğŸ¾ Supervision"
type = "page"
target = "supervision"
href = "/supervision"

[[navigation]]
title = "ğŸ“ Teaching"
type = "page"
target = "teaching"
href = "/teaching"

#[[navigation]]
#title = "Awards"
#type = "page"
#target = "awards"
#href = "/awards"

[[navigation]]
title = "ğŸ‘œ Services"
type = "page"
target = "services"
href = "/services"

#[[navigation]]
#title = "CV"
#type = "page"
#target = "cv"
#href = "/cv"

[[navigation]]
target = "talk"
href = "/talk"
type = "page"
title = "ğŸ¯Talk"

[[navigation]]
target = "old_news"
href = "/old_news"
type = "page"
title = "Old News"
