type = "card"
title = "Services"
description = "Professional services and community involvement."


[[items]]
title = "Reviewer"
subtitle = "ACL 2026, EACL 2026"
date = "2026"

[[items]]
title = "Reviewer"
subtitle = "IJCNLP-AACL 2025, EMNLP 2025, ACL 2025, COLING 2025, ICLR 2025, NAACL 2025"
date = "2025"

[[items]]
title = "Reviewer"
subtitle = "ARR December"
date = "2024"
